// <auto-generated />
using System;
using BlogApp.Data.Concrete.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogApp.Data.Migrations
{
    [DbContext(typeof(BlogAppContext))]
    [Migration("20230111185102_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.12");

            modelBuilder.Entity("BlogApp.Entity.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorPhoto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("ArticleId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            ArticleId = 1,
                            AuthorName = "Sezenler Olmuş",
                            AuthorPhoto = "1_en.jpeg",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "1.jpeg",
                            IsApproved = true,
                            IsDeleted = false,
                            IsHome = true,
                            Name = "How to be a devoloper",
                            Url = "technology-software"
                        },
                        new
                        {
                            ArticleId = 2,
                            AuthorName = "Kuzu kuzu",
                            AuthorPhoto = "2_en.jpeg",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "2.jpeg",
                            IsApproved = true,
                            IsDeleted = false,
                            IsHome = true,
                            Name = "Endüstri 4.0 Gerçekten Nedir? Tüm Çalışanları Nasıl Etkileyecek?",
                            Url = "technology-industry"
                        },
                        new
                        {
                            ArticleId = 3,
                            AuthorName = "oy dağlar",
                            AuthorPhoto = "3_en.jpeg",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "3.jpeg",
                            IsApproved = true,
                            IsDeleted = false,
                            IsHome = true,
                            Name = "Android Geliştirici Seçenekleri ile Neler Yapabilirsiniz?",
                            Url = "technology-android"
                        },
                        new
                        {
                            ArticleId = 4,
                            AuthorName = "senin paran",
                            AuthorPhoto = "4_alm.jpeg",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "4.jpeg",
                            IsApproved = true,
                            IsDeleted = false,
                            IsHome = false,
                            Name = "Turkish cuisine",
                            Url = "turkish-cuisine"
                        },
                        new
                        {
                            ArticleId = 5,
                            AuthorName = "burda geçmez",
                            AuthorPhoto = "5_alm.jpeg",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "5.jpeg",
                            IsApproved = true,
                            IsDeleted = false,
                            IsHome = false,
                            Name = "Chinese cuisine",
                            Url = "chinese-cuisine"
                        },
                        new
                        {
                            ArticleId = 6,
                            AuthorName = "Queen",
                            AuthorPhoto = "6_alm.jpeg",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "6.jpeg",
                            IsApproved = false,
                            IsDeleted = false,
                            IsHome = true,
                            Name = "French cuisine",
                            Url = "french-cuisine"
                        },
                        new
                        {
                            ArticleId = 7,
                            AuthorName = "otomasyon fan",
                            AuthorPhoto = "7_ital.jpeg",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "7.jpeg",
                            IsApproved = true,
                            IsDeleted = false,
                            IsHome = false,
                            Name = "Classic Music",
                            Url = "art-music"
                        },
                        new
                        {
                            ArticleId = 8,
                            AuthorName = "Dudu dudu",
                            AuthorPhoto = "8_ital.jpeg",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "8.jpeg",
                            IsApproved = true,
                            IsDeleted = false,
                            IsHome = false,
                            Name = "Cinema",
                            Url = "art-cinema"
                        },
                        new
                        {
                            ArticleId = 9,
                            AuthorName = "namık kemal",
                            AuthorPhoto = "9_ital.jpeg",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "9.jpeg",
                            IsApproved = true,
                            IsDeleted = false,
                            IsHome = false,
                            Name = "Painters",
                            Url = "art-painters"
                        },
                        new
                        {
                            ArticleId = 10,
                            AuthorName = "orham kemal",
                            AuthorPhoto = "10_kor.jpeg",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "10.jpeg",
                            IsApproved = true,
                            IsDeleted = false,
                            IsHome = false,
                            Name = "places to visit in Italy",
                            Url = "travel-italy"
                        },
                        new
                        {
                            ArticleId = 11,
                            AuthorName = "yaşar kemal",
                            AuthorPhoto = "11_kor.jpeg",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "11.jpeg",
                            IsApproved = true,
                            IsDeleted = false,
                            IsHome = true,
                            Name = "First settlement",
                            Url = "travel-first-settlement"
                        },
                        new
                        {
                            ArticleId = 12,
                            AuthorName = "yaşar yaşamaz",
                            AuthorPhoto = "12_kor.jpeg",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            DateAdded = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "12.jpeg",
                            IsApproved = true,
                            IsDeleted = false,
                            IsHome = true,
                            Name = "The nature beauty Kaş",
                            Url = "travel-kaş"
                        });
                });

            modelBuilder.Entity("BlogApp.Entity.ArticleCategory", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ArticleId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ArticleCategories");

                    b.HasData(
                        new
                        {
                            ArticleId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            ArticleId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            ArticleId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            ArticleId = 4,
                            CategoryId = 2
                        },
                        new
                        {
                            ArticleId = 5,
                            CategoryId = 2
                        },
                        new
                        {
                            ArticleId = 6,
                            CategoryId = 2
                        },
                        new
                        {
                            ArticleId = 7,
                            CategoryId = 3
                        },
                        new
                        {
                            ArticleId = 8,
                            CategoryId = 3
                        },
                        new
                        {
                            ArticleId = 9,
                            CategoryId = 3
                        },
                        new
                        {
                            ArticleId = 10,
                            CategoryId = 4
                        },
                        new
                        {
                            ArticleId = 11,
                            CategoryId = 4
                        },
                        new
                        {
                            ArticleId = 12,
                            CategoryId = 4
                        });
                });

            modelBuilder.Entity("BlogApp.Entity.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Technology Category",
                            Name = "Technology",
                            Url = "technology"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Food Category",
                            Name = "Food",
                            Url = "food"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Art Category",
                            Name = "Art",
                            Url = "art"
                        },
                        new
                        {
                            CategoryId = 4,
                            Description = "Travel Category",
                            Name = "Travel",
                            Url = "travel"
                        });
                });

            modelBuilder.Entity("BlogApp.Entity.ArticleCategory", b =>
                {
                    b.HasOne("BlogApp.Entity.Article", "Article")
                        .WithMany("ArticleCategories")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogApp.Entity.Category", "Category")
                        .WithMany("ArticleCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BlogApp.Entity.Article", b =>
                {
                    b.Navigation("ArticleCategories");
                });

            modelBuilder.Entity("BlogApp.Entity.Category", b =>
                {
                    b.Navigation("ArticleCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
